### PR TITLE
Add links to get the app

### PR DESCRIPTION
**Pull request by Poussinou**

### CODE REVIEW

**Comment by ramschmaerchen** [comment]
Currently only released on F-Droid. Play Store release follows eventually.

**Comment by ramschmaerchen** [comment]
Sry for temporary close, I thought this is an issue ^^.
I will pull as soon as it's available on Play.

**Comment by Poussinou** [comment]
The link to google play store doesn't point to your app? I can remove it or change it if you want

**Comment by ramschmaerchen** [comment]
It does, but we did not release on Play yet.

**Comment by Poussinou** [comment]
Ok^^

**Pull request closed without merging**
